name: ShortcutFoundation-macOS

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-11
    
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      
    - name: Build and Test
      run: xcodebuild clean build test -scheme "ShortcutFoundation" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
